# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 17:09
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('addition_date', models.DateTimeField(verbose_name='Time of addition')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Average rating')),
                ('rating_count', models.IntegerField(verbose_name='Count of ratings')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ('average_rating',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addition_date', models.DateField(auto_now=True, verbose_name='Date of addition')),
                ('paid_for', models.BooleanField(verbose_name='Paid for tour')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('addition_date',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('begin_date', models.DateField(verbose_name='Date of the beginning')),
                ('end_date', models.DateField(verbose_name='Date of the ending')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cost')),
                ('contact_details', models.CharField(max_length=200, verbose_name='Contact details')),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', through='travel_agency_api.Comment', to=settings.AUTH_USER_MODEL)),
                ('reservations', models.ManyToManyField(blank=True, related_name='reservations', through='travel_agency_api.Reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ('begin_date', 'cost'),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_tour', to='travel_agency_api.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='rating',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency_api.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency_api.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_tour', to='travel_agency_api.Tour', verbose_name='Tour'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
