# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_agency_api', '0002_auto_20161213_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('address', models.CharField(max_length=150, verbose_name='Description')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_tour', to='travel_agency_api.Tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
